### ISSUE TITLE
Добавление подсветки для тикеров, торгующихся через Тинькофф.Инвестиции, на определённых сайтах

### ISSUE THREAD

**Issue by akarakotov** [almirus/broker_tcs#27]
Контекст: на finance.yahoo.com, finviz и подобных сайтах часто идут новости о тикерах, и совершенно непонятно, стоит ли обращать на них внимание. Сейчас приходится лезть  в терминал и проверять доступность этих тикеров, занимает кучу времени.

Предложение такое, для ряда сайтов из списка сделать цветовое или ещё какое выделение тикеров:
- тикер доступен в Т.Инвестиции неквалифицированному инвестору
- тикер доступен в Т.Инвестиции только квалифицированному инвестору
- тикер недоступен в Т.Инвестиции

Реагировать на отдельные слова 1-5 символов в верхнем регистре.

Данные брать из OpenAPI, /market/stocks, /market/bonds, /market/etfs, /market/currencies

**Comment by almirus** [comment]
не совсем понял, вы предлагаете чтобы плагин модифицировал контент на других сайтах?

**Comment by akarakotov** [comment]
Да, модифицировать контент на других сайтах, все верно.

**Comment by almirus** [comment]
логичнее наверно будет это отдельно вынести в другой плагин

**Comment by akarakotov** [comment]
Можно и вывести в отдельный, можно и в этом, т.к. эта фича для пользователей Тинькофф Инвестиций, есть подключение к терминалу, который, кстати,может добавить полезности в виде подсвечивания тикеров в избранном или участвующих в сделке. 

С точки зрения простоты реализации — да, наверное, лучше в отдельный плагин.

**Comment by almirus** [comment]
@akarakotov напишите пока домены на которых по вашему необходимо добавить информацию

**Comment by akarakotov** [comment]
Я думаю, у каждого список источников будет свой, для старта можно начать с этого списка:
- finance.yahoo.com
- finviz.com
- investing.com
- tradingview.com

**Comment by almirus** [comment]
готово https://github.com/almirus/TinkoffTicker жду апрува от Google

**Comment by almirus** [comment]
@akarakotov 

https://chrome.google.com/webstore/detail/tinkoffticker/dpflhleimmbhmcihedanghbdeoinpiig

**Comment by akarakotov** [comment]
Спасибо большое, поставил, буду тестить!
