### ISSUE TITLE
Не отображается портфель

### ISSUE THREAD

**Issue by apv174ru** [almirus/broker_tcs#28]
После обновления версии расширения до 0.9.6 перестал отображаться портфель.
До обновления была версия 0.9.1 - в ней портфель отображался. Ошибка в консоли [error.txt](https://github.com/almirus/broker_tcs/files/4859107/error.txt)
![scr1](https://user-images.githubusercontent.com/1585524/86267161-beb73400-bbdf-11ea-80fe-f22b79927e8d.png)

**Comment by almirus** [comment]
F5 не помогает?

**Comment by apv174ru** [comment]
> F5 не помогает?

Нет

**Comment by almirus** [comment]
выпустил обновление, должно помочь, если нет, просьба нажать правую кнопку на иконке, выбрать Управление расширением, отладка страницы, background.html и оттуда скинуть лог

**Comment by apv174ru** [comment]
Спасибо, помогло)
